#!/usr/bin/env bash

set -e

export SOLOCLI_WORKDIR=$(cd $(dirname $0) && pwd)

echo $SOLOCLI_WORKDIR
  
if [ ${UID} == 0 ]; then
    echo 'You cannot run Solo as the root user' >&2
    exit 1
fi

show_help() {
    cli_name=${0##*/}
    cli_version=$(cat $SOLOCLI_WORKDIR/VERSION) || "0.0.1"

    echo "
Solo-CLI
Version: $cli_version
Usage: $cli_name [command]"
    exit 1
}

validate_args() {
    arg_size="${#}"

    if [ ${arg_size} -lt 1 ] || [ "${*}" == "--help" ]; then
        show_help
        exit 0
    fi
}

main() {
    validate_args "${@}"
}

## Entry point function

main "${@}"